// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfD8sTAbAnBIM7PZ8qvOemlUkU9PN10w0',
    appId: '1:1067823960365:web:5c3be9fbfb604ec9bf03a4',
    messagingSenderId: '1067823960365',
    projectId: 'qaoautomation',
    authDomain: 'qaoautomation.firebaseapp.com',
    storageBucket: 'qaoautomation.firebasestorage.app',
    measurementId: 'G-CFWSH2168V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfXaYybdtCa3GooKfolTfRIAa-OvO3Oys',
    appId: '1:1067823960365:android:9c3f9444a9bf4296bf03a4',
    messagingSenderId: '1067823960365',
    projectId: 'qaoautomation',
    storageBucket: 'qaoautomation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXjqkIuf8XbhLm9l-JbP2_FQ6zTRVT2-Y',
    appId: '1:1067823960365:ios:038f5c9380b1fd8cbf03a4',
    messagingSenderId: '1067823960365',
    projectId: 'qaoautomation',
    storageBucket: 'qaoautomation.firebasestorage.app',
    iosBundleId: 'com.example.lyceumNotif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXjqkIuf8XbhLm9l-JbP2_FQ6zTRVT2-Y',
    appId: '1:1067823960365:ios:038f5c9380b1fd8cbf03a4',
    messagingSenderId: '1067823960365',
    projectId: 'qaoautomation',
    storageBucket: 'qaoautomation.firebasestorage.app',
    iosBundleId: 'com.example.lyceumNotif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfD8sTAbAnBIM7PZ8qvOemlUkU9PN10w0',
    appId: '1:1067823960365:web:64b351bbde4c39d8bf03a4',
    messagingSenderId: '1067823960365',
    projectId: 'qaoautomation',
    authDomain: 'qaoautomation.firebaseapp.com',
    storageBucket: 'qaoautomation.firebasestorage.app',
    measurementId: 'G-LCG818HB4J',
  );
}
